# Test Macro for G4LowEFrag 
# (can be run in batch, without graphic)
#
#
/control/verbose 2
/run/verbose 2
#
#/run/numberOfThreads 1
#
#
#####################################
# BIC RUN
/physics/setIonInelasticProcess bic
#
/run/initialize
#
/process/list
# /process/inactivate hadElastic
/process/inactivate ionElastic
#
/histoManager/setFileName bic
#
/run/printProgress 100
/run/beamOn 1000
#
#
#####################################
# INCL RUN
/physics/setIonInelasticProcess incl
#
/run/initialize
#
/process/list
# /process/inactivate hadElastic
/process/inactivate ionElastic
#
/histoManager/setFileName incl
#
/run/printProgress 100
/run/beamOn 1000