# $Id$
#
# Macro file for "LowEFrag"
# (can be run in batch, without graphic)
#
#
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/process/setVerbose 0
#
#
/physics/setIonInelasticProcess bic
#
# /run/numberOfThreads 16
#
/run/initialize
#
#
# /process/list
# /process/inactivate hadElastic
/process/inactivate ionElastic
#
#
/histoManager/setFileName /outputs/bic.xml
#
/run/printProgress 100000
#
# /run/beamOn 1000000
/run/beamOn 10000

