# $Id$
#
# Macro file for "Hadr03.cc"
# (can be run in batch, without graphic)
#
# list process
#
/control/verbose 2
/run/verbose 2
#
#
/physics/setIonInelasticProcess bic
#
#/run/numberOfThreads 1
#
/run/initialize
#
#
/process/list
# /process/inactivate hadElastic
/process/inactivate ionElastic
#
#
/histoManager/setFileName /outputs/bic.xml
#
/run/printProgress 10000
#
#/run/beamOn 1000000
/run/beamOn 10000
