name: Apptainer Build Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    container:
        image: carlomt/apptainer:1.3.2
        options: --privileged

    name: Build Container
    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v4

      - name: Build Container
        run: |
           cd containers   
           singularity build  LowEFrag.sif Apptainer.def

      - name: Login and Deploy Container
        run: |
           echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
           singularity push LowEFrag.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
