name: Pull and Run Apptainer Container unit test

on:
  workflow_run:
    workflows: ["Apptainer Build and Deploy"]
    types:
      - completed

jobs:
  pull-and-run-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    container:
      image: carlomt/apptainer:1.3.2
      options: --privileged

    name: Pull and Run Container
    steps:

      - name: Set tag and repo lowercase
        id: setup
        run: |
          if [ "${{ github.event.workflow_run.event }}" = "push" ]; then
            TAG=${{ github.event.workflow_run.head_sha }}
          else
            TAG="pr-${{ github.event.workflow_run.pull_requests[0].number }}-${{ github.event.workflow_run.head_sha }}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lower=$REPO_LOWER" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GHCR_PAT }} | singularity registry login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io

      - name: Pull Container from GHCR
        run: |
          singularity pull LowEFrag.sif oras://ghcr.io/${{ steps.setup.outputs.repo_lower }}:${{ steps.setup.outputs.tag }}

      - name: Run the container
        run: |
          echo "Running container..."
          singularity run LowEFrag.sif 
