name: Container unit test

on:
  workflow_run:
    workflows: ["Apptainer Build and Deploy"]
    types:
      - completed

jobs:
  pull-and-run-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    container:
      image: carlomt/apptainer:1.3.2
      options: --privileged

    name: Pull and Run Container
    steps:

      - name: Set tag and repo lowercase
        id: setup
        run: |
          TAG=${{ github.event.workflow_run.head_sha }}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lower=$REPO_LOWER" >> $GITHUB_OUTPUT

      - name: Set SIF filename
        id: set_sif
        run: |
          sif_file=$(echo "${{ github.repository }}" | awk -F/ '{print $2}')  # estrae solo "LowEFrag"
          echo "sif=${sif_file}.sif" >> $GITHUB_OUTPUT

          
      - name: Login to GHCR
        run: |
          echo ${{ secrets.GHCR_PAT }} | singularity registry login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io

      - name: Pull Container from GHCR
        run: |
          singularity pull ${{ steps.set_sif.outputs.sif }} \
          oras://ghcr.io/${{ steps.setup.outputs.repo_lower }}:${{ steps.setup.outputs.tag }}

      - name: Restore Geant4 data from cache
        id: g4data-cache
        uses: actions/cache@v4
        with:
          path: /tmp/g4data
          key: geant4-data-v1

      - name: Download Geant4 data libraries (if cache miss) using geant4-config
        if: steps.g4data-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/g4data
          apptainer exec --unsquash -B /tmp/g4data:/g4data \
          ${{ steps.set_sif.outputs.sif }} \
          bash -c "geant4-config --install-datasets"

          
      - name: Run the container
        run: |
          echo "Checking datasets..."
          apptainer run \
          --unsquash \
          -B /tmp/g4data:/g4data:ro \
          ${{ steps.set_sif.outputs.sif }} \
          bash -c "ls /g4data && geant4-config --check-datasets"
          echo "Running container..."
          apptainer run \
          --unsquash \
          -B /tmp/g4data:/g4data:ro \
          ${{ steps.set_sif.outputs.sif }} \
          /workspace/macro/unit.mac


