name: Create Project Entries from Macros

on:
  workflow_run:
    workflows: ["Pull and Run Apptainer Container unit test"]
    types: [completed]
  workflow_dispatch:
    inputs:
      dummy:
        description: "Manually start"
        required: false
        default: ""

jobs:
  populate-project:
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
      REPO: ${{ github.repository }}
      ORG: G4Med-test
      PROJECT_NUMBER: 1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to populate GitHub Project
        run: python .github/scripts/populate_github_project.py
