name: INFN runner long

on:
  workflow_run:
    workflows: ["INFN run unit"]
    types:
      - completed

jobs:
  pull-and-run-container:
    runs-on: aiinfn-runner-g4

    steps:
      - name: Set tag and repo lowercase
        id: setup
        run: |
          if [ "${{ github.event.workflow_run.event }}" = "push" ]; then
            TAG=${{ github.event.workflow_run.head_sha }}
          else
            TAG="pr-${{ github.event.workflow_run.pull_requests[0].number }}-${{ github.event.workflow_run.head_sha }}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lower=$REPO_LOWER" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GHCR_PAT }} | singularity registry login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io

      - name: Pull Container from GHCR
        run: |
          singularity pull LowEFrag.sif oras://ghcr.io/${{ steps.setup.outputs.repo_lower }}:${{ steps.setup.outputs.tag }}
          
      - name: Prepare singularity command
        run: |
          cat <<EOF > /home/runner/run
          singularity exec \
            --unsquash \
            -B /cvmfs/geant4.cern.ch/share/data:/opt/geant4/data  \            
            -B /tmp/runner/_work:/home/runner/_work \
            -B /tmp/outputs:/outputs \
            oras://ghcr.io/${{ steps.setup.outputs.repo_lower }}:${{ steps.setup.outputs.tag }} \
            "\$@"
          EOF
          mkdir -p /tmp/runner/_work
          mkdir -p /tmp/outputs
          chmod +x /home/runner/run
          cat /home/runner/run

      - name: Check cvmfs
        run: |
          ls /cvmfs/geant4.cern.ch
          /home/runner/run bash -c "geant4-config --check-datasets"          
          
      - name: Run the container
        run: |
          echo "Running container..."
          /home/runner/run /workspace/build/LowEFrag /workspace/macro/bic.mac
          /home/runner/run /workspace/build/LowEFrag /workspace/macro/incl.mac          

      - name: Upload simulation outputs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: simulation-outputs
          path: /tmp/outputs/          
