name: test apptainer infn

on:
  push:
    branches:
      - main

jobs:
  run-on-apptainer:
    # Specifica che questo job deve girare su un runner self-hosted
    runs-on: aiinfn-runner-g4
    
    steps:
      - name: 1. Checkout del codice
        uses: actions/checkout@v4

      - name: 2. Verifica l'installazione di Apptainer
        run: |
          echo "Verifico la versione di Apptainer:"
          apptainer --version
          echo "Verifico chi sta eseguendo il processo:"
          whoami

      - name: 3. Esegui un comando base in un'immagine remota
        run: |
          echo "Eseguo 'cat /etc/os-release' nell'immagine Alpine..."
          apptainer exec library://alpine cat /etc/os-release

      - name: 4. Interagisci con i file del repository dall'interno del container
        run: |
          echo "Creo un file di test nella workspace del runner..."
          echo "Questo è un file di prova" > file_di_test.txt
          
          echo "Elenco i file nella workspace dall'interno di un container Ubuntu:"
          # Apptainer monta automaticamente la directory di lavoro corrente
          # $GITHUB_WORKSPACE sarà quindi accessibile all'interno del container
          apptainer exec library://ubuntu:22.04 ls -la $GITHUB_WORKSPACE
          
          echo "Leggo il file di test dall'interno del container:"
          apptainer exec library://ubuntu:22.04 cat $GITHUB_WORKSPACE/file_di_test.txt
