name: Test INFN runner unit2

on:
  workflow_run:
    workflows: ["Apptainer Build and Deploy"]
    types:
      - completed

jobs:
  pull-and-run-container:
    runs-on: aiinfn-runner-g4

    steps:
      - name: Set tag and repo lowercase
        id: setup
        run: |
          if [ "${{ github.event.workflow_run.event }}" = "push" ]; then
            TAG=${{ github.event.workflow_run.head_sha }}
          else
            TAG="pr-${{ github.event.workflow_run.pull_requests[0].number }}-${{ github.event.workflow_run.head_sha }}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lower=$REPO_LOWER" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GHCR_PAT }} | singularity registry login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io

      - name: Prepare singularity command
        run: |
          cat <<EOF > /home/runner/run
          singularity exec \
            --unsquash \
            -B /tmp/g4data:/opt/geant4/data  \
            oras://ghcr.io/${{ steps.setup.outputs.repo_lower }}:${{ steps.setup.outputs.tag }} \
            "\$@"
          EOF
          mkdir -p /tmp/g4data
          chmod +x /home/runner/run
          cat /home/runner/run
          
      - name: Restore Geant4 data from cache
        id: g4data-cache
        uses: actions/cache@v4
        with:
          path: /tmp/g4data
          key: geant4-data-v1

      - name: Download Geant4 data libraries (if cache miss) using geant4-config
        if: steps.g4data-cache.outputs.cache-hit != 'true'
        run: |
          /home/runner/run bash -c "geant4-config --install-datasets"

          
      - name: Run the container
        run: |
          echo "Running container..."
          /home/runner/run /workspace/build/LowEFrag /workspace/macro/unit.mac
