name: INFN run unit

on:
  workflow_run:
    workflows: ["Container unit test"]
    types:
      - completed

jobs:
  pull-and-run-container:
    runs-on: aiinfn-runner-g4

    steps:

      - name: Set Apptainer Cache and Temp Directories
        run: |
          mkdir -p /tmp/apptainer_cache
          mkdir -p /tmp/apptainer_tmp
          mkdir -p /tmp/runner
          echo "APPTAINER_CACHEDIR=/tmp/apptainer_cache" >> $GITHUB_ENV
          echo "APPTAINER_TMPDIR=/tmp/apptainer_tmp" >> $GITHUB_ENV          
      
      - name: Set tag and repo lowercase
        id: setup
        run: |
          TAG=${{ github.event.workflow_run.head_sha }}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lower=$REPO_LOWER" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GHCR_PAT }} | singularity registry login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io

      - name: Pull Container from GHCR
        run: |
          singularity build --sandbox /tmp/container oras://ghcr.io/${{ steps.setup.outputs.repo_lower }}:${{ steps.setup.outputs.tag }}
          
      - name: Prepare singularity command
        run: |
          cat <<EOF > /tmp/runner/run
          apptainer run \
          -B /cvmfs/geant4.cern.ch/share/data:/g4data  \
          -B /tmp/runner/_work:/tmp/runner/_work \
          /tmp/container \
          "\$@"
          EOF
          mkdir -p /tmp/runner/_work
          chmod +x /tmp/runner/run
          cat /tmp/runner/run
      
      - name: Check cvmfs
        run: |
          ls /cvmfs/geant4.cern.ch
          /tmp/runner/run bash -c "geant4-config --check-datasets"
      
      - name: Run the container
        run: |
          nproc
          echo "Running container..."
          /tmp/runner/run /workspace/macro/unit.mac
